# Generated by Django 2.2 on 2019-04-25 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(default=99999)),
                ('code', models.TextField(unique=True)),
                ('name', models.TextField()),
                ('category', models.TextField()),
                ('feature_code', models.TextField()),
                ('type', models.TextField()),
                ('description', models.TextField(null=True)),
                ('enable', models.BooleanField(default=True)),
                ('backend', models.TextField(default='common')),
                ('display', models.BooleanField(default=True)),
                ('subtemplate', models.TextField(null=True)),
                ('location', models.TextField()),
                ('params', models.TextField(null=True)),
            ],
        ),
    ]
